{% set name = "vibehdf5" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vibehdf5-{{ version }}.tar.gz
  sha256: 97d4c2dcf2c14ad8c754ee59aa88b40567ce6834ca8e35066c360859ce7211e9

build:
  entry_points:
    - vibehdf5 = vibehdf5.hdf5_viewer:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - h5py >=3.0.0
    - numpy >=1.20.0
    - qtpy >=2.4.3
    - pandas >=1.3.0
    - matplotlib-base >=3.5.0

test:
  imports:
    - vibehdf5
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - pyside6

about:
  summary: A lightweight GUI to browse and interact with HDF5 file structures
  home: https://pypi.org/project/vibehdf5/
  dev_url: https://github.com/jacobwilliams/vibehdf5
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobwilliams
